spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer_db?useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # Hibernate 属性，SQL 方言使得 Hibernate 为所选数据库生成更好的 SQL
        show_sql: true//显示sql语句
        format_sql: true//输出格式化后的sql,更方便查看
        use_sql_comments: true//是否显示注释，用于指示出是什么操作产生了这个SQL语句。
        generate_statistics: false//如果开启, Hibernate将收集有助于性能调节的统计数据.

